version: "3"
services:
  reverseproxy:
      image: philiphabib/reverseproxy:v7
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed
  backend-user:
    image: philiphabib/udagram-api-user:v7
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://a7c48e54f83b9410ab4128a0c706b822-1028603296.eu-west-2.elb.amazonaws.com:8100"
  backend-feed:
    image: philiphabib/udagram-api-feed:v7
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://a7c48e54f83b9410ab4128a0c706b822-1028603296.eu-west-2.elb.amazonaws.com:8100"
  frontend:
    image: philiphabib/udagram-frontend:v7
    ports:
      - "8100:80"
